### ISSUE TITLE
guide/documentation

### ISSUE THREAD

**Issue by Medie1** [asmaloney/GDExtensionTemplate#65]
Hi Andy, i messaged you on Mastodon before.

Your repo is really helpful, thanks! Though coming from UE, which has its own closed-source build system, i've found it quite difficult to understand how you setup the build process. This is because i've only recently started getting into Cmake.

I think it would benefit people like myself, who haven't had prior experience in cmake, to have a more documented repo, maybe just comments? Or perhaps a small markdown file?

That said, you've helped me understand cmake and GDExtension a lot with this repo, thanks a bunch!

**Comment by asmaloney** [comment]
Hi Medie.

I've looked at what I've got in the repo and and I'm not quite sure what specifically you're asking for. The CMake files are all commented to outline what they are doing at each stage.

If you're asking for an intro to CMake, then that's outside the scope of this project. There are many, many resources for learning CMake that do a way better job than I ever could. I've found [An Introduction to Modern CMake](https://cliutils.gitlab.io/modern-cmake/) a pretty good resource.

If you're asking for something else, then could you maybe clarify?
